### ISSUE TITLE
domain constraints

### ISSUE THREAD

**Issue by MaxOstrowski** [MaxOstrowski/clingo#12]
- think about adding domain constraints `&dom{100..999;0} = x`

**Comment by rkaminsk** [comment]
With initial propagation, we can equivalently write `100 <= x <= 999.` as a constraint.

**Comment by MaxOstrowski** [comment]
You forgot about the 0. Punching holes manually like:
```
0 <= x <= 100.
{a}.
x <= 20 :- a.
x >= 80 :- not a.
```
does not propagate the same as having explicitly domains with holes.
On the other hand, with domains with holes you sometimes have to do logarithmic search using lower/upper_bound(...) functions during propagation.

**Comment by rkaminsk** [comment]
Sorry for the German but I don't want to translate this into English.

Bist du sicher? Sobald irgendein `x<=n` mit 20 < n < 80 wahr wird, wird `x >= 
80` falsch und somit `a` und `x<=20` wahr. Wenn ein `x<=n` mit 19 < n < 79 
falsch wird, wird `x <= 20` falsch und damit werden `a` und 'x<=79` falsch. Es 
wird also alles wesentliche propagiert. Es werden jedoch sinnlose 
Ordervariablen eingeführt, die mit deiner Variante vermieden werden und nicht 
extra wieder rausresolviert werden müssen. Die Propagation sollte aber die 
gleiche sein.

Es bringt bestimmt etwas diesen Fall zu optimieren. Es ist nur die Frage, ob 
derartige Konstrukte in der Praxis oft genug auftauchen, so dass der Aufwand 
gerechtfertigt ist (obwohl das vermutlich gar nicht so schwierig ist). 
Generell finde ich Domänenanweisungen häßlich, weil es "unnötige" 
Sprachkonstrukte sind, die rein für die Optimierung der Implementation 
eingeführt wurden. Auf der anderen Seite, sehe ich clingcon aber auch als 
Lowlevel-Sprache für Übersetzungen wie lc2casp an. Von daher sollte man 
eventuell doch Domänenanweisungen einbauen, solange man das nicht in sowas wie 
lc2casp schreiben muss.

**Comment by rkaminsk** [comment]
I implemented domain constraints in 01da417922aa6f3b27f2d2c1e17677f218c1bcf4 by translating them to unary sum constraints. The translation should be propagation friendly. Everything is chained. Compared to the native handling, with this translation we might get more order literals but propagation strength should be the same.

**Comment by rkaminsk** [comment]
Now that I implemented the translation I also realized, that this can be translated much better.

Consider `x` in `{[1,2], [4,5], [7,8]}`. We can simply add the binary constraints:
- right to left
  - `true` => `x <= 8`
  - `x < 7` => `x <= 5`
  - `x < 4` => `x <=2`
- left to right
  - `true` => `x >= 1`
  - `x > 2` => `x >= 4`
  - `x > 5` => `x >= 7`

This does not introduce any auxiliary literals and results in very simple clauses.

**Comment by MaxOstrowski** [comment]
That actually looks quite nice.

**Comment by rkaminsk** [comment]
Commit b67a2d987324097515611ad96a55aa3d2646d996 now implements the improved translation.

**Comment by rkaminsk** [comment]
We still don't have support for domains with holes such that no order literals are introduced for holes. The current implementation is hopefully good enough in practice.
