### ISSUE TITLE
Support for theory atoms with conditional elements.

### ISSUE THREAD

**Issue by MaxOstrowski** [MaxOstrowski/clingo#13]
The constraint

    &sum { x : a + y : b } <= 10.

can be rewritten into

    &sum { xa + yb } <= 10.
    &sum { xa } = a :- a.
    &sum { xa } = 0 :- not a.
    &sum { yb } = b :- b.
    &sum { yb } = 0 :- not b.

Similar rewriting can be applied to `&minimize` and `&distinct` constraints.
    
Note: We could also think about how to handle this natively without introducing additional variables. But it is probably best to delay this until we have a real application where we need this.

**Comment by rkaminsk** [comment]
This is a big step and we should probably ignore it for now.

**Comment by rkaminsk** [comment]
I don't think that it is essential to have this in clingcon and would rather not implement anything yet.

**Comment by MaxOstrowski** [comment]
Agreed
