### ISSUE TITLE
Multi Thread/Shot Bug in Clasp/Clingo

### ISSUE THREAD

**Issue by MaxOstrowski** [MaxOstrowski/clingo#23]
On branch bug/multi 
"SKIPCHECK" in csp/__init__.py prevents bug from occuring (sometimes) in unittest:
`python -m unittest csp.tests.test_csp.TestMain.test_optimize`

**Comment by rkaminsk** [comment]
I created a small script to reproduce the bug. You can checkout `bug/multi3` to have a look. I will still port this to C++ so that it is easier for Benny to have a look and then submit in clasp's repository. Reproduce with: `python reproduce.py`.

**Comment by rkaminsk** [comment]
Let's see what Benny says: potassco/clasp#52.

**Comment by rkaminsk** [comment]
It should be fixed in the latest clingo version. Please give it a try.
