### ISSUE TITLE
Propagation Strength

### ISSUE THREAD

**Issue by MaxOstrowski** [MaxOstrowski/clingo#4]
- have different options for propagation strength p (dependent on strict/non-strict too)
- p >=1 propagate constraints that are assign true but violate bounds
- p >=2 propagate constraints that are not yet assigned to true/false depending on the current lower/upper bounds
- p >=3 propagate new bounds for variables of constraints that are assigned to true
- p >=4 propagate constraints that are not yet assigned to true/false depending on the "smaller" current lower/upper bounds

**Comment by rkaminsk** [comment]
Does that really make any sense? We get stronger propagation at virtually no extra cost, i.e., we have to loop over the literals in a constraint anyway. Detecting literals to propagate just adds a constant factor (even though the eager reason generation makes it slightly more expensive).

**Comment by MaxOstrowski** [comment]
I agree with this. Nevertheless, I do not think that we have p>=2 functionality (if a constraint atom is still undecided but the constraint can never be fulfilled given the current bounds, it has to become false).
Related to this is p>=4, where a smaller reason can be generated at log cost in my implementation but it should be constant with continious domains.

Nevertheless: p>=2 is not for free as we have to check unassigned constraints for this one.

**Comment by rkaminsk** [comment]
The current implementation also checks unassigned constraints. Its literal is propagated in line 780.
