### ISSUE TITLE
Alldifferent Constraints

### ISSUE THREAD

**Issue by MaxOstrowski** [MaxOstrowski/clingo#6]
- add support for alldifferent constraints {a_0*v_0; ...; a_n*v_0}
  - pairwise inequality 
  - using cardinality constraints 
```
1 {a_0*v_0==17; ...; a_n*v_n==17} 1
1 {a_0*v_0==17; ...; a_n*v_n==18} 1
...
1 {a_0*v_0==17; ...; a_n*v_n==178} 1
```

**Comment by rkaminsk** [comment]
Maybe it is better to add a propagator for this? The first translation is quadratic and the second does not scale well with the domain size. I think that implementing a propagator would not even be difficult.

Note that the quadratic translation can also be implemented in clingo-dl if the coeffcients are 1.

Your example looks just wrong. But I guess I know what you mean.

**Comment by MaxOstrowski** [comment]
Still don't know why it looks wrong but an extra propagator sounds like a good idea.
The only caveat is that we need to share the knowledge about the order literals, maybe even write access.

**Comment by rkaminsk** [comment]
I would implement it in the same propagator adding another function but we can discuss this offline. Regarding the example:
```
{a_0*v_0==min; ...; a_n*v_n==min} 1
...
{a_0*v_0==0;   ...; a_n*v_n==0  } 1
{a_0*v_0==1;   ...; a_n*v_n==1  } 1
{a_0*v_0==2;   ...; a_n*v_n==2  } 1
...
{a_0*v_0==max; ...; a_n*v_n==max} 1

```
