### ISSUE TITLE
General linear constraints as input

### ISSUE THREAD

**Issue by MaxOstrowski** [MaxOstrowski/clingo#7]
- support any linear constraints independent of form
- normalize to `a_0 * v_0 + ... a_n * v_n <= rhs` using gcd and sorted by smallest domain, on tie, largest coefficient

**Comment by rkaminsk** [comment]
To me it looks like this goes hand in hand with better reason generation. For generating shorter reasons, we should probably order by lower/upper bound times coefficient preferring values that make the slack as small as possible.

**Comment by MaxOstrowski** [comment]
Sorting is still missing, everything else already done.
